-- 코드를 입력하세요
SELECT c.ANIMAL_ID, c.NAME
FROM (SELECT i.ANIMAL_ID, DATEDIFF(o.DATETIME, i.DATETIME)AS CUL_DATE, i.NAME
      FROM ANIMAL_INS i JOIN ANIMAL_OUTS o
      ON i.ANIMAL_ID = o.ANIMAL_ID) AS c
ORDER BY c.CUL_DATE DESC LIMIT 2
