-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, ROUND((c.DAILY_FEE * 30) * (1 -  (0.01* p.DISCOUNT_RATE))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY r
ON c.CAR_ID = r.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_ID NOT IN(SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
                     AND p.DURATION_TYPE = '30일 이상'
GROUP BY c.CAR_ID
HAVING c.CAR_TYPE IN ('세단', 'SUV') AND FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC 