-- 코드를 입력하세요
SELECT i.REST_ID AS REST_ID, i.REST_NAME AS REST_NAME, i.FOOD_TYPE AS FOOD_TYPE, i.FAVORITES AS FAVORITES, i.ADDRESS AS ADDRESS, ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS i JOIN REST_REVIEW AS r ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC