-- 코드를 입력하세요
SELECT s.YEAR, s.MONTH, i.GENDER, COUNT(i.USER_ID) AS USERS
FROM USER_INFO i JOIN (SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
                       FROM ONLINE_SALE) s
ON i.USER_ID = s.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY s.YEAR, S.MONTH, i.GENDER
ORDER BY s.YEAR, S.MONTH, i.GENDER
