-- 코드를 작성해주세요
SELECT e.ID, e.GENOTYPE, f.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA e JOIN (SELECT ID, GENOTYPE
                       FROM ECOLI_DATA) f
ON e.PARENT_ID = f.ID
WHERE e.GENOTYPE & f.GENOTYPE = f.GENOTYPE
ORDER BY ID