SELECT 
    e.YEAR,
    (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM (
    SELECT 
        ID, 
        SIZE_OF_COLONY, 
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
) e
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) m
ON e.YEAR = m.YEAR
ORDER BY e.YEAR ASC, YEAR_DEV ASC;
