-- 코드를 작성해주세요
SELECT g.SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE GROUP BY EMP_NO) g
ON e.EMP_NO = g.EMP_NO
ORDER BY g.SCORE DESC LIMIT 1