WITH INFO_CTE AS (
SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
FROM FISH_INFO
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM INFO_CTE
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC